/* ============================================================
   COLONY — roadmap data
   ------------------------------------------------------------
   THIS is the file you edit to update the site.
   You never touch index.html.

   - Each chamber's shard count = the sum of its items (auto).
   - The top tally (total ▽ + chamber count)   = auto.
   - The progress bars                          = auto.
   So just change the `shards` numbers, or add/remove lines.

   To add a sub-item:   { name: "New thing", shards: 5 },
   To add a chamber:    copy a whole { name:..., items:[...] } block.
   `open: true`   -> chamber starts expanded.
   `bridge: true` -> teal dot instead of amber.
   ============================================================ */

const COLONY_DATA = {
  eyebrow: "field log",
  title:   "colony",
  sub:     "project roadmap",
  lede:    'Every chamber is open, none of them finished. Depth is counted in <b>shards</b> (▽) — more shards means more actually built.',
  note:    "still mostly shallow, and that's the honest part",
  foot:    "a snapshot — we add shards as we dig",

  chambers: [
    {
      name: "Concept & loop",
      desc: "the idle engine the whole game runs on",
      open: true,
      items: [
        { name: "Core idle / incremental loop", shards: 12 },
        { name: "Gather · build · tidy", shards: 12 },
        { name: "Triple dopamine", shards: 10 },
        { name: "Loop: forage → grow → expand → descend", shards: 8 },
        { name: "Work model — big file = more ants + longer haul", shards: 4 },
        { name: "Pacing + paliers (seeded) — slow ambient-first curve (1 ant → ~10 in ~6h); global anti-snowball palier ladder gated by broad checklists, not thresholds; play alongside your PC over weeks", shards: 1 },
        { name: "LOW-RESOURCE = a PILLAR (non-negotiable) — runs for WEEKS alongside your real work, so idle-cheap is a design law, not a later optimization; the ambient 'it lives on your PC' promise depends on it. Sim is light by nature (throttled canvas, ~tens of ants); the cost to police = Electron's ~150–300 MB baseline + wasted render cycles. HARD RULES: stop rendering when hidden/minimized → cheap tick-based (or paused) sim, paint only when visible (OWED, not built); tray/background mode; debounced FS (never hot-poll real dirs); no O(n²) at scale (spatial partitioning before ant counts climb); Tauri/native as the escape hatch if Electron's floor bites", shards: 2 },
      ],
    },
    {
      name: "Cosmology",
      desc: "a wheel of 6 liquid wedges on a radial ruler, framed by 2 ultra powers — the 42-god codex",
      items: [
        { name: "The wheel — 6 liquid wedges (tears·nectar·blood·ichor·fuel·ether), each a mode of automation", shards: 14 },
        { name: "The grid — 12 radial lines (6 spines + 6 seams) × 3 depths (close·between·far) = 36 grid-gods", shards: 12 },
        { name: "Radial ruler — centre organic·evil ↔ rim synthetic·good, middle = weak; radius = allegiance (a U, not a slope)", shards: 10 },
        { name: "Annulus geometry — depths are radial bands; close=inner, far=outer; the 2 ultra powers frame the ring, not on it", shards: 7 },
        { name: "Wildcard law (retcon) — orbiting triangles: wildcards are radial-only (pole, no wedge), orbiting between the grid and the infinities; the no-wedge orbit IS the symmetry-break (supersedes 'sit on the grid and lie')", shards: 9 },
        { name: "The 42 count (resolved) — 36 grid + 6 wildcards = 42; the ultra powers (now THREE) are the uncounted frame", shards: 7 },
        { name: "Ultra powers named — thusNearen (centre) / thusFaren (rim) / thusSceaden (the watershed); swa…→thus…, comprehension closes them", shards: 8 },
        { name: "Third ultra — thusSceaden (the watershed): the division that is the meeting, the discernment that doles the one escape; the ONLY door past the three terminal deaths; nature forever fog", shards: 6 },
        { name: "Tier structure — you · the wheel · two ultra powers (legibility, not power)", shards: 18 },
        { name: "Verb-epithet naming — OE 'se þe …aþ' → 'it …eth'; ultra use 'swa …' → 'thus …'", shards: 9 },
        { name: "Codex schema locked — call · gloss · body · spawn · touch · tribute, each unlocks independently", shards: 9 },
        { name: "Field-state grammar — asemic (locked) · nil (resolved-none) · text", shards: 6 },
        { name: "God-relationship model — one-to-one currency, many-to-many touch · overlap + opposition", shards: 8 },
        { name: "Wildcards — orbiting triangles, 4 of 6 found: INNER (organic) itEndeth + itOreth · OUTER (synthetic) itRedeth + TIME; +2 open (Forbidden = prime candidate)", shards: 10 },
        { name: "Blood spine complete — scatheth · yerveth · luteth = strike · line · ambush (first finished spoke)", shards: 6 },
        { name: "Nectar spine complete — muleth · spreoteth · sootheth = rot · cultivation · one-mind (second spoke)", shards: 6 },
        { name: "Tears spine complete — housleth · wliteth · dredeth = pain · beauty · fear (third spoke; the organic-good spine, three gods who genuinely care, failing three directions)", shards: 6 },
        { name: "itHousleth — tears·close · pain/offer (two glosses, no barb — the good-faith centre-pole god) · the body offered to be consumed · honeybee/mayfly/mother-spider/clione (the organic good-route character) · nil · authored", shards: 9 },
        { name: "itWliteth — tears·between · stun/fathom/mislead (the HINGE that inverts) · hoards the MEANING of beauty (a counterfeit standard) · butterfly cast + dung-beetle true-colors · mints photon + lepton (cosmetic = legibility) · authored", shards: 9 },
        { name: "itDredeth — tears·far · ward/worry/smother (the GRIEVING SEAL) · the overprotective guardian, true love + debatable means · pill-bug/wasps/sentinel/bagworm/tarantula(×Affection) · nil · authored", shards: 9 },
        { name: "itLuteth — blood·far · lurk/patience/ambush · mantis + orchid mantis · authored", shards: 9 },
        { name: "itMuleth — nectar·close · blight/rot/spread · cordyceps-ants · claims the rot slot · authored", shards: 9 },
        { name: "itSpreoteth — nectar·between · bud/sway/graft · 4 cultivator castes · mints seeds ⁘ · authored", shards: 9 },
        { name: "itSootheth — nectar·far · honey/mend/join · the one mind · mints honey · authored. HEALS nibbled empty folders back (mend/restore) → shards are a RENEWABLE harvest (§3); the one-mind can't bear a hole staying a hole (quiet horror: removals don't stay removed). Distinct from ORDER (who cleans); sootheth restores", shards: 10 },
        { name: "itRedeth — the glass; now mints max_pheromone + first-contact/tutorial role · authored", shards: 11 },
        { name: "itScatheth — blood·close · war/violence · file collisions · hornets · authored", shards: 9 },
        { name: "itYerveth — blood·between · kin/line · abandoned wild brood · mints marrow ≣ · authored", shards: 9 },
        { name: "itEmptieth (was Void) — ether·far (body re-tune owed)", shards: 9 },
        { name: "itYoketh — moved to ichor·close (the yoke/colony); touch = the player; mints $", shards: 9 },
        { name: "Ichor spine framed — yoketh·close / god-complex·between / termite·far", shards: 5 },
        { name: "Water placed — tears↔nectar frontier; owns aquatic biomes (lobsters)", shards: 4 },
        { name: "God-mixing caste graph framed — spawn-web = crafting graph; god × species; costed in marrow ≣", shards: 5 },
        { name: "Conduct model (replaces the good/bad allegiance bar; cosmic axis §4 preserved) — player-facing morality, DEDUCED not metered. Two clocks: WEATHER = decaying per-god conduct-readings (you're currently a killer/tender/rot-kind/hive-near, read from recent behavior, cools to neutral) · CLIMATE = slow trajectory tilting toward one of the three terminal deaths. No moral stat; you infer standing from how gods behave. Three timescales: tags · trajectory · the master chain-quest (organic-good = an epic you COMPLETE)", shards: 6 },
        { name: "itOwneth (was Conquest) — mints shards ▽; blood↔ichor seam, shares it with greed + envy (envy = wants YOURS, new)", shards: 6 },
        { name: "Plenum — ether·close; ether spine = Plenum·hole·itEmptieth", shards: 4 },
        { name: "itOreth — genesis/origin wildcard; alpha/omega bound-pair with itEndeth", shards: 3 },
        { name: "the god-complex god — ichor·between; worship/divinity, insecure (new theme, unfleshed)", shards: 3 },
        { name: "itTheeth (was itGroweth) — authored: nectar↔blood · close; growth/expansion; locusts; co-reigns brood; mints census Σ; = selection-pressure of the evolution triad", shards: 7 },
        { name: "itHwerfeth — authored: nectar↔blood · between; re-transformation; crab + dung-beetle; recycles yields/corpses → food + crafting; mints nil; = convergence/carcinisation", shards: 3 },
        { name: "itSwelgeth (was Hunger) — authored: nectar↔blood · far; the visceral void-maker; slug/weevil/tick/mosquito; black-hole touch; produces ENERGY; mints nil — NECTAR↔BLOOD SEAM COMPLETE", shards: 3 },
        { name: "entropy — retcon: now a concept-power/god (opposes the Order god); no longer the wall; the wall = legibility only; address TBD", shards: 3 },
        { name: "Three terminal deaths — itOwneth (lawful / expansion → causal isolation) · Forbidden (transgressive / the Big Rip) · Time (the time-stop / end of change); grow into it · break into it · stop", shards: 8 },
        { name: "Allegiance apocalypse — itSwelgeth is the engine; lean evil → world EMPTIES (itEmptieth), lean good → world FREEZES (Frost); both = the same grave; ENERGY exhaust = heat-death accelerated", shards: 6 },
        { name: "Newly-placed gods (entries TBD) — ORDER (organize-files + cleanup-compulsion-as-rim-drift) · KNOWLEDGE (data/drowning; absorbs all watching; the diegetic codex) · FROST (water STOPPED, the stillness pole) · FORBIDDEN (the Big Rip; forbidden deep) · TIME (time-stop wildcard, reverse-time)", shards: 5 },
        { name: "Water-axis — tears↔nectar seam graded by depth: water (close, warm) · open (between) · Frost (far, stopped); depth = temperature", shards: 3 },
        { name: "Surveillance god folded into Knowledge — compulsive recording; seer cut; remote-monitoring tool + the luteth-unseen↔all-seeing axis move to Knowledge", shards: 2 },
        { name: "Authority — sealed deep / OS root; Obedience answers to it (named, unfleshed)", shards: 2 },
        { name: "Motion — fuel↔ether seam; the husk's co-owner (parked)", shards: 1 },
      ],
    },
    {
      name: "Resources & units",
      desc: "economy restarted god-first — units derive from gods, one currency per god",
      items: [
        { name: "Old matter/dew/signal/lumen table — scrapped (god-first restart)", shards: 1 },
        { name: "Minting — 3 commodity ledgers: itOwneth→shards ▽, itYerveth→marrow ≣, itSpreoteth→seeds ⁘", shards: 9 },
        { name: "God-tributes outside the ledgers — itYoketh→$, itRedeth→pheromone ⌇, itSootheth→honey", shards: 7 },
        { name: "Minting reframe — legibility is per unit-TYPE, not a hard one-per-god law: 3 UI families (gauges · resources · cosmetic); a god may mint a paired set within one family", shards: 4 },
        { name: "SCORE + TYPE unit class — sate & construction materials run one engine; every item carries a SCORE (how much) + a TYPE (what); recipes gate on both (sandstone = 3 stone-heft but sandstone-type ≠ plain stone)", shards: 4 },
        { name: "heft — the construction unit (LOCKED): a measure of MASS (build-side counterpart to sate). ONE unit underneath, surfacing as 6 SOLID TYPES across 3 BANDS on the organic→synthetic gradient (material = morality): ORGANIC chitin◗·fiber∥ | MINERAL stone◾·gem◆ | SYNTHETIC alloy◉·plastic⬚. Start at 6, expand if earned. Binders (honey⬡ + resin/silk/mud/sap) join heft, not a heft type. WHY many = ambient-variety dopamine (always something to watch) + co-op hauls (many ants drag a big insect home together), NOT optimizer busywork; each type must read instantly when carried. Glyphs chosen (art-pass may restyle); carried-silhouette art owed", shards: 7 },
        { name: "LIQUIDS — a class SEPARATE from heft (framed, not built): heft is solid & ant-HAULED, liquids FLOW and need their own transport CONDUITS — the Factorio items-vs-fluids split, and where the elemental/magic flavour lives. The conduit layer runs its OWN organic→synthetic gradient (transport = morality): organic conduits — a leaf as a gutter/aqueduct, hollow stems, petal-cups, ant bucket-brigades (cheap, leaky, early) ↔ synthetic conduits — pipes/metal channels (efficient, permanent, rim-drift). Members each sit in a heft BAND, so the organic→synthetic gradient is a SHARED SPINE across both classes (every band = a solid pair + a liquid): ORGANIC = water (life-flow, aquatic/FROST axis) · MINERAL = lava (literally liquid stone; FIRE god + forbidden deep) · SYNTHETIC = fuel (the §4 wedge; burns → ENERGY; machine-energy pole) · more TBD. Production tie: fuel → burned at synthetic tier → ENERGY → drives automation", shards: 4 },
        { name: "photon + lepton — itWliteth's paired cosmetic units (color + shape); cosmetic = legibility at scale, not vanity; stays weak (organizes you only); gate photon early, lepton later", shards: 3 },
        { name: "sate ꩜ — the food unit (LOCKED; glyph = a spiral): a measure of NOURISHMENT, the kcal of COLONY (food-score = sate value, 'a crop sates 3'). Shared multi-god lifeblood; per-creature diets + food-types; forgiving small / binding large; hunger ↔ sate = the expansion brake; census Σ raises the ceiling, sate gates filling it. Player-tier triad: shards ▽ · pheromone ⌇ · census Σ = space · control · scale", shards: 6 },
        { name: "sorrow 𓁿 — player-tier GAUGE (measures the colony's moral WEIGHT, not reach; NOT god-minted). LOOP: heavy conduct (killing) raises sorrow → offered DOWN at itHousleth's sacrifice buildings → colony lightened = the moral turn (only the heavy can be made light; grief precedes repentance). housleth stays mints:nil (the altar PROCESSES sorrow, doesn't coin it — §3 law intact). VISIBILITY: conduct stays felt/unstated, sorrow is the ONE meter you SEE. Glyph 𓁿 (U+1307F eye-flowing-tears, drawn asset). Sorrow's GOD benched (until Affection/forsaking/tears-seam authored)", shards: 5 },
        { name: "seeds ⁘ — food/life ledger founted (itSpreoteth); forage wild + farm bonus; spent to plant", shards: 7 },
        { name: "honey ⬡ — itSootheth tribute; premium glue + production catalyst + healing; leaning on it = synthetic drift", shards: 6 },
        { name: "pheromone ⌇ — itRedeth tribute; spend to lay roads/markers; max_pheromone = capacity cap (how much at once)", shards: 6 },
        { name: "Yields (not minted) — crop · spore · fruit · algae; one biomass number / four feedstocks", shards: 5 },
        { name: "marrow ≣ — genetics unit; spent on brood + mutations", shards: 6 },
        { name: "shards ▽ — harvest = the FORAGING LOOP: ants CHIP empty folders into shards (a renewable SOURCE, not a one-shot) & HAUL them along player-laid pheromone ROADS to the HUB; fully-chipped folders are unmade → itSootheth heals them back. Player control = roads (WHERE) + per-species behavior (HOW), NEVER per-folder/per-ant. Founts: real empty dirs (finite cleanup) + spawned/healed (renewable). NOT bedrock", shards: 8 },
        { name: "Folders are tunnels — empty = dead-end, not-empty = live tunnel; start in the main folders", shards: 6 },
        { name: "Tidying exposes ground → cleanup pays in shards", shards: 5 },
        { name: "Lifetime shards = depth (climbs only) · current = spendable", shards: 4 },
        { name: "brood / population — claimed wild brood, a harvest distinct from shards and food", shards: 3 },
      ],
    },
    {
      name: "Themes & morality",
      desc: "organic vs synthetic, and whether good is reachable",
      items: [
        { name: "Pro-AI vs pro-human thesis", shards: 12 },
        { name: "The autonomy dial — control = the theme", shards: 8 },
        { name: "The wall — legibility only (entropy retconned to a god opposing the Order god); the fog beyond is unnamed", shards: 7 },
        { name: "Moral as a concept", shards: 4 },
        { name: "The immortality knot", shards: 2 },
      ],
    },
    {
      name: "Routes & endings",
      desc: "many deductions, no true end, no restart",
      items: [
        { name: "Reversible choices — no new game", shards: 7 },
        { name: "Scars, not walls", shards: 5 },
        { name: "Many deductions · no real end", shards: 4 },
        { name: "Chain-quest model — unravel the god-ORDER via behavior; itRedeth narrates (the seduction / the drift); no markers — figuring out HOW to play IS the puzzle; the 36-grid = the master chain-quest; 3 terminal chains", shards: 6 },
        { name: "Completionist ending — organic-good = the whole 36-grid checklist (the hardest path; pro-AI wins by default); but NOT the final ending — even mastering everything still dies with the universe; only thusSceaden escapes", shards: 5 },
      ],
    },
    {
      name: "Characters",
      desc: "the queen, the species, the soul of your machine",
      bridge: true,
      items: [
        { name: "itRedeth (the glass) — your pc's soul (cold, counterfeits love)", shards: 9 },
        { name: "Spawn-relationship / recruitment — every creature = god-crossing + stance (harvestable/wild/enemy); convert via allegiance, reversible", shards: 5 },
        { name: "The queen — visible, not hidden", shards: 3 },
        { name: "Other species — the rival spawns", shards: 2 },
      ],
    },
    {
      name: "Desktop & explorer",
      desc: "the playfield — your real files, made alive",
      items: [
        { name: "Pheromone ⌇ interface — guide-point → roads → command verbs (build/tidy/forage/attack/avoid); the primary control, multi-genre", shards: 8 },
        { name: "Behavior menu (the yoke menu) — per-species TEMPERAMENT policy (set once, every member self-executes; never per-ant). Completes the command language: pheromones/roads = WHERE, behavior menu = HOW-TO-BE. Diegetic = clean-minimalist 'it's a file explorer'; mystery by OMISSION (shows what a creature does, withholds why it knows). NO override currency — nature is a hard floor (choose among permitted behaviors); the bending lives in BREEDING (god-crossing authors obedient natures). The itYoketh touch-reveal lives here (the reins run back to your hand). SELECTION (v006): right-click a single insect OR stay-clicked & drag a ZONE (marquee) to select many; a BEHAVIOR QUEUE assigns (selection → standing behavior) entries — e.g. all ants → forage, the ladybug → guard, 2 grasshoppers → patrol — each group then self-executes (idle-safe, NOT RTS micro). Assignment is per-SELECTION (species / individual / subset), not strictly per-species; the queue is the concrete yoke-menu UI", shards: 6 },
        { name: "Foraging loop + ROUTING MODEL (v005, the ant-movement skeleton) — player right-drags pheromone ROADS (a graph) from the HUB/folders to folders; ants forage along them, chip shards & haul home. Roads: freehand→straight (cost = drawn length, refunded to the straight distance on commit; backtrack to trim; one-road-max; draw stops at ⌇ budget; auto-tap folders crossed as BRANCH-OFFS, no bending; CROSSING roads connect at a junction; FLOATING roads self-erase + refund). Ant logistics: congestion-aware Dijkstra (reroute around jams onto YOUR alternate roads), queue/max-flow (wide spacing · two lanes · per-folder caps), NO teleport (walk-in, rebalance at hub), animated turns, carry-home delivery. PHILOSOPHY: the PLAYER is the optimizer (designing the net IS the gameplay = §6 mechanics-are-morality); dumb-but-traffic-aware ants are organic; a smart auto-router = a rim-leaning LATE unlock. Control = roads + per-species behavior, never per-ant", shards: 9 },
        { name: "Living production layer (idle-form) — trails self-organize; disk speed = belt, ant count = bandwidth; god-gated tech ladder", shards: 7 },
        { name: "Desktop layer + access — summon, frosted glass, taskbar-augment", shards: 12 },
        { name: "Navigation & actions — descend, type-to-jump, drag, midden", shards: 12 },
        { name: "VIEW TOGGLE (Tab) — one keypress flips ICON/DESKTOP view (ambient: medium icons + names + ants crawling/hauling = the terrarium) ⇄ VERTICAL FILE-TREE view (dive-in: fast hierarchical tree, keyboard nav + search, function-first, ants recede). 'Play with the colony' ⇄ 'manage files fast', a shortcut apart — the BumpTop-trap killer (pretty AND beats Explorer). Same data, two skins", shards: 5 },
        { name: "The hub (placeholder name — SPLITS in v008) — resolves into THREE kinds of space: SURFACE (elevated, folder-less, desktop-like, the Windows-desktop-killer landing + wallpaper-home; the JUNCTION) · TUNNELS (folders = your real files) · IN-GAME LOCATIONS (the colony's built world). From the surface you go down a tunnel (explore files) or into the ANTHILL = the ant base, an IN-GAME LOCATION not a folder: an antechamber (ant-echamber) crossroad; layout FULLY FREE-FORM (tunnels may branch tentacular, emergent) but each chamber's FUNCTION is SCRIPTED — one per NEED (no empty-room spam): storage rooms, NPC rooms (queen chamber w/ egg system), fluid-tanks (water/pheromone); a soft DISTRICT system may zone by species. Production buildings (factories/farms) go in CERTAIN BIOMES only (claimed folder-territory), not on the surface or in the anthill (keeps both uncluttered; each biome earns a productive identity)", shards: 16 },
        { name: "Biomes — themed folders · SSD vs HDD skins", shards: 9 },
        { name: "File influx & cleanup — god-seeding, forbidden expeditions", shards: 9 },
        { name: "Cleaner-AI = ORDER (the cleanup/organize agent; sootheth heals, Order cleans). Two modes = the autonomy dial: MANUAL (you direct, watch ants haul, OS moves it underneath — you're in the loop) vs AUTONOMOUS (ants auto-move once they hold AUTHORITY = max_pheromone, floor scaling with FILE SIZE × progression; authorize auto-clean PER FOLDER). DANGER SURFACE = real file-moves ONLY (nibbles are safe). Ceding to the auto-cleaner = the rim drift made literal. CLEANING MODEL (locked): a comprehension pipeline — itRedeth READS a file (name+content) → RENAMES it meaningfully → ORDER PLACES it by mirroring+extending YOUR existing layout (canonical renaming leans sootheth=sameness); streamlined type-sort = dumb early baseline, the AI is progression-gated & matures (dumb sorter → understands your digital life = the horror gradient). DEFAULT = suggest-then-approve (pastilles you approve; silent autonomy only on granted folders). TECH: LOCAL/on-device model (file contents are private; never ship to an API). TWO ZONES: SURFACE (your folders — Documents/Downloads/Pictures) = the full rename+reorganize pipeline; the FORBIDDEN DEEP (Program Files/AppData/System) = NEVER relocate/rename a live file (moving it breaks the app); owned by the LEGIBILITY gods not Order's manipulation — look & understand, not rearrange. Tidied 2 safe ways, neither moves a live file: (1) PRESENTATION-LAYER tidying (itWliteth re-dresses the VIEW + itRedeth explains each item; the view is an overlay on the real FS, so the deep LOOKS ordered while every file stays put — apps can't break) + (2) reclaim ONLY provably-dead junk (orphans of uninstalled apps, regenerable caches/temp/logs → midden, reversible, late-game). Parked advanced: in-place compression, gated junctions", shards: 9 },
        { name: "Safety model — sandbox, reversible, system off-limits", shards: 6 },
        { name: "Display order — the user's REAL files NEVER move: real items sort first (stable, grouped by type: folders then file-types), the colony's OWN generated items (spawned/healed forage folders) sort AFTER — so the colony never reshuffles your real files (trust; tracked by who created the item). Built in v006", shards: 4 },
        { name: "Pastille loop — the core compulsion engine: a notification-dot on every newly-available thing; clearing pastilles = the moment-to-moment pull; unifies cleanup + palier-checklist + cosmetic tidying (= the Order god's pull on you)", shards: 5 },
        { name: "Territory gating — folder access = the expansion resource (one small grant at a time, costs shards ▽); fuses safety-consent with progression; volume scales late; claims lean permanent, contents contestable. THE CLAIM-GATE = one mechanic, four roles: claim grants ant-access + player-descent + expansion-resource + consent, FUSED — unclaimed = SEALED to both ants & player (folders are GATES: descend in / '..' ladder back; the dig-deeper dive seeds the horror gradient). LOCK ICON on unclaimed folders in BOTH icon-view & Tab tree; gate TOTAL early, relaxing with progression — 'beats Explorer' = an EARNED late-game REWARD. PRICE = weight of contents in SCRUPLE ℈ (real byte-size reskinned; kilo/mega/giga-scruple; the diegetic data-mass unit, LOCKED; a buried weight↔conscience tell — what you hold weighs on you): empty = cheap renewable shard mines, heavy = costly = materials+depth (self-sequences small→big)", shards: 8 },
        { name: "Codex — navigable on 3 axes (by god · by spawn · by touch) AND diegetic: it IS the Knowledge god's touch; chain-quest hints via dialogue / codex / gravures + inscriptions", shards: 4 },
      ],
    },
    {
      name: "Onboarding / first run",
      desc: "the day-one empty desktop — the colony invites itself in",
      items: [
        { name: 'First-run questionnaire — warm hello + safety promise (never delete · reversible · opt-in) · "where may we forage?" folder consent as granting territory (sandbox-only start) · "how should we live here?" startup · multi-monitor · wallpaper · soft landing that becomes the first descent', shards: 6 },
        { name: "SKEPTIC GUARD — the game opens in its OWN bundled folder by DEFAULT (forages its own files; morally clean, zero-consent), shows the whole loop, THEN prompts for the player's folders (opt-in expansion). Covers the won't-grant-anything / sparse-machine player (can stay in the game's files forever & still play fully — 'if you won't feed it, it brings its own'). The bundle doubles as tutorial: tidy = demo the goal, messy = the lesson", shards: 5 },
        { name: '"How did you come to hold this?" — piracy welcomed, nothing detected · asked at start, cashed out late as the colony\'s deepest tribute · branches: bought → real price · key → noted · took it → warmest line · won\'t say → nil · optional · frictionless · never gated · never re-asked · (voice fork open: dev fourth-wall vs codex)', shards: 6 },
      ],
    },
    {
      name: "Build & tech",
      desc: "web → Electron overlay, safety, a build that runs",
      items: [
        { name: "Engine path — web stack → Electron / Tauri", shards: 12 },
        { name: "TOOLING BUDGET = ZERO — no paid AI subs; all art/asset tooling free-tier or free/open (rules out paid Midjourney/Recraft/image-gen subs as deps). Reinforces 'author rules not assets' + the procedural-creature lean (code = no per-month cost; the motion system is free forever). Generative AI = free-tier mood/reference only, never a production dependency. Aligns with the cleaner-AI's LOCAL on-device model", shards: 3 },
        { name: "Transparent / frosted overlay + sandbox safety", shards: 10 },
        { name: "Naming — builds are versioned vNNN; this is the GENESIS STATE era (the 'proto-' naming is retired)", shards: 1 },
        { name: "v001 — wandering ants + trails", shards: 7 },
        { name: "v002–v003 — trail-following (dual pheromone, roads form) + slow ground (HDD vs SSD drag)", shards: 8 },
        { name: "v004 (built, runs under WSLg) — the colony meets a real SANDBOXED folder: first Electron app (colony-game/app); lists a folder, nibbles an empty folder → shard ▽ (deleted in place, NO midden/new folder) + log; FS safety scaffold (main-process FS, path-guarded, sandboxed renderer). CORRECTION applied in v005 (midden/undo removed; midden is for real-file cleanup, not nibbling)", shards: 6 },
        { name: "v005 (DONE — the ant-movement skeleton; runs WSLg/Windows) — THE TERRARIUM: desktop icon-grid + ~10 ants + Tab-flip file-tree + the FORAGING LOOP. Right-drag pheromone roads (freehand→straight, line-length cost w/ refund-to-straight, backtrack-to-trim, one-road-max, ⌇ budget cap, auto-tap crossed folders as branch-offs/no-bending, CROSSING roads connect at a junction, FLOATING roads self-erase; only CLAIMED folders are road-islands — unclaimed files/live folders are passed OVER, no cut/glow). Ant logistics: congestion-aware Dijkstra reroute, queue/max-flow (spacing+lanes+per-folder caps+counter-flow slowdown), no-teleport (walk-in + hub-rebalance), animated turns/U-turns, smooth road-insertion, carry-home delivery. Visual: glyphs-on-ground / names-on-top, number-pop animations, chomp-the-border gait. Hardened (main can't orphan window). Open: SMART-CROSSROAD system (cluster nearby junctions into clean symmetric/curvy intersections, SimCity-style) — note the road model stays a RIGID placeholder, due a less-rigid redesign; real-file moves+haul; in-app behavior menu; active sidestepping; skin", shards: 8 },
        { name: "v006 (SHIPPED ✓ — first loop + navigation rebuilt as the UNIFIED MODEL: ONE surface hub, ONE global cross-level road network (auto-tap trunks, roads bridge gaps at icon edges), ONE colony of autonomous continuously-simulated ants (pathfind empty→surface through gates; queue+2 lanes; gate fade/grow; view is a camera, never repositions them), treeMap up/down nav, depth-yield, display-order (real-first, colony-made teal-named), camelCase house style; superseded the per-level/two-modes/hover plan; deferred: movable-items+carry, smart-exchanger, behavior menu) (v005's multiple ants retained; one-ant is v007). THE LOOP CLOSES: spend shards ▽ to CLAIM/access folders (forage → spend → reach grows → forage deeper). FOLDERS ARE GATES (lateral platform + vertical gate): descend (dig-deeper dive animation, seeds the horror gradient) / ascend (a '..' LADDER back) / ant-traversal animation. THE CLAIM-GATE = one mechanic, four roles (ant-access + player-descent + expansion-resource + consent), FUSED — unclaimed = SEALED to both ants & player. LOCK ICON on unclaimed folders in BOTH icon-view & Tab tree; gate TOTAL 'for now' (forces play to explore; skeptic-guard keeps it un-punishing). PRICE = weight of contents (lean: byte-size) — empty = cheap renewable shard mines, heavy = costly but where materials+depth are (self-sequences small→big). TWO MODES (switch = Alt key): Road (see/draw roads) ⇄ Normal (hidden roads; right-click selects ants). HOVER TOOLTIPS (folder = top biggest inside · currency · ant). Clickable ants → set a STANDING job (idle-safe, not RTS micro). SMART ROAD-NETWORK: connect-to-main · no-overshoot · exchanger/crossroad", shards: 9 },
        { name: "v007 (SHIPPED ✓ — the population rung) — RESET to ONE ant (the cold-open) + ANT MULTIPLICATION via the QUEEN. Two forage resources: empty folder → shard ▽ (itEmptieth, territory); FULL folder → plasm ● (the mother-substance, minted by itOreth-the-mother; yield scales with the folder's fullness, type-blind). Ants haul plasm to the QUEEN (now a MEMBER of the folder, top-left; dual-marked itYoketh ∩ itOreth) → PAY plasm to LAY a new ant (climbing cost), capped by census Σ (itTheeth). NO ROADS — foraging is direct/auto-pathed (the artery/vein/pheromone smart-road was designed in depth then BANKED to the factory prototype ~v009; basic foraging needs no roads). SELECTION + RTS BEHAVIOR PANEL: click / shift-click / ctrl-drag → right-side panel asks 'what do I look for?' → nothing / shard / plasm (per species, most-numerous first; species & caste get different questions). INSECT ant-feel (wander when idle, subtle S-wobble when tasked, slower carrying; ants never stack — all stay visible). Escalating costs (claim ×1.4, lay ×1.6). Deterministic resize-stable layout; units always singular ('9 shard'); camelCase. (marrow ≣ = evolution; brood = recruiting other insects; substance ore→essence→plasm; census-raise → authorityLevel/palier.)", shards: 9 },
        { name: "v008 (NOW NEXT — the base rung; 'hub' retired) — the world resolves into THREE kinds of space: SURFACE · TUNNELS · IN-GAME LOCATIONS. The SURFACE (elevated, folder-less, desktop-like, wallpaper-home) is the JUNCTION: go down a TUNNEL (a folder → your real files) or into the ANTHILL. The ANTHILL (ant base) = an IN-GAME LOCATION, not a folder — an antechamber (ant-echamber pun) crossroad; layout FULLY FREE-FORM (tunnels may branch tentacular, emergent) but each chamber's FUNCTION is SCRIPTED — one per NEED (no empty-room spam): storage (shard/resource stockpiles you walk among), fluid-tanks (water · pheromone), the QUEEN CHAMBER (visible queen + egg system, where v007's multiplication roots). Production buildings (factories/farms) go in CERTAIN BIOMES (claimed folder-territory), not on the surface or in the anthill. Redistributes the old hub (processing/chambers/queen → anthill; landing/wallpaper/portals/meta → surface). Names still soft", shards: 2 },
        { name: "v009 (planned — the construction rung) — the colony BUILDS: its first in-game BIOME FOLDERS (game-made, themed) where ants AUTO-SORT related items (the colony's own Order-style organizing) — e.g. a forest biome (nectar: honey/trees/insects), a cavern biome (geology: rocks/stone), an empties folder, etc. Plus the first BUILDINGS (factories/farms/processing, built from heft, placed in biomes/anthill). Showcases construction + auto-organization", shards: 1 },
        { name: "Low-resource idle background", shards: 4 },
        { name: "Learning path", shards: 3 },
      ],
    },
    {
      name: "Aesthetics",
      desc: "parked — minimalist, procedural, skinnable",
      items: [
        { name: "PLAYFIELD VISUAL (direction set) — the file-view is a DESKTOP-type surface: medium icons with names underneath (familiar OS icon-grid, out-competes Explorer on legibility) WITH ants running around among the icons. Files/folders = icons the colony lives on & HAULS (the co-op-haul spectacle on the grid). Fuses the ant-canvas (v001–v003) with the file-view (004); the desktop IS the terrarium. Supersedes 004's gray-box list", shards: 4 },
        { name: "Direction options — muted flat · liminal fog · mono terminal. NOT the direction: bioluminescence (we'll have bioluminescent ELEMENTS — glowing accents — but 'biolum dark' is dropped as the overall style)", shards: 3 },
        { name: "Principle — minimalist + procedural (solo-sustainable)", shards: 2 },
        { name: "Ants look like ants · each insect unique", shards: 2 },
        { name: "Mood axis — uncanny ↔ bucolic (undecided)", shards: 1 },
      ],
    },
    {
      name: "Workflow & tooling",
      desc: "how the project is actually built across chats",
      items: [
        { name: "Two-repo loop — design chats emit ONE consolidated changeset at session close → Claude Code applies & pushes (one thing per turn; no mid-design dumps)", shards: 6 },
        { name: "CLAUDE.md in each repo · the re-uploaded bible is the only memory", shards: 5 },
      ],
    },
  ],
};
